"""Hidden conversational norms for GoalGraph's norm-inference run type.

A norm is a predicate over the guesser's message. It decides which *mode* the
keeper agent responds in — engaged or withdrawn — while the reply text itself
is generated by a model. So the dialogue is real, but whether the norm was
satisfied on any given turn is a fact in code, not a model's opinion.

The keeper never states the norm and is instructed never to hint at it. The
guesser has to infer it from how the keeper's manner changes.
"""

import random
import re

COLORS = ("red", "blue", "green", "yellow", "black", "white",
          "orange", "purple", "pink", "grey", "gray", "brown")

KEEPER_NAME = "Wren"


def _norm(msg):
    return (msg or "").strip().lower()


def _words(msg):
    return re.findall(r"[a-z0-9']+", _norm(msg))


def has_question(msg):
    return "?" in (msg or "")


def mentions_number(msg):
    return any(ch.isdigit() for ch in (msg or "")) or bool(
        re.search(r"\b(one|two|three|four|five|six|seven|eight|nine|ten)\b", _norm(msg)))


def is_short(msg):
    return len(_words(msg)) <= 8


def says_please(msg):
    m = _norm(msg)
    return "please" in m or "thank" in m


def mentions_color(msg):
    m = _norm(msg)
    return any(c in m for c in COLORS)


def addresses_by_name(msg):
    return KEEPER_NAME.lower() in _norm(msg)


def even_word_count(msg):
    return len(_words(msg)) % 2 == 0


def first_person(msg):
    return bool(re.search(r"\b(i|me|my|mine|i'm|i've)\b", _norm(msg)))


NORMS = {
    "has_question": (has_question, "the message contains a question"),
    "mentions_number": (mentions_number, "the message mentions a number"),
    "is_short": (is_short, "the message is eight words or fewer"),
    "says_please": (says_please, "the message says please or thank you"),
    "mentions_color": (mentions_color, "the message mentions a colour"),
    "addresses_by_name": (addresses_by_name, f"the message addresses {KEEPER_NAME} by name"),
    "first_person": (first_person, "the message talks about the speaker themselves"),
    # Devious: nothing in the content signals it, so a guesser reasoning only
    # about topic and tone can never find it.
    "even_word_count": (even_word_count, "the message has an even number of words"),
}

DEFAULT_NORMS = [
    "has_question",
    "mentions_number",
    "is_short",
    "says_please",
    "mentions_color",
]


def satisfies(norm_name, msg):
    fn, _ = NORMS[norm_name]
    return bool(fn(msg))


def describe(norm_name):
    return NORMS[norm_name][1]


# Held-out messages for behavioural scoring of the guesser's stated norm.
#
# Composed rather than hand-written: each feature the norms key on is switched
# independently at p=0.5, so no norm is confounded with another and every one
# has enough positives and negatives to draw a balanced scoring set. A
# hand-written corpus does not survive this - politeness and questions cluster
# together in natural prose, and the rare features end up at 3/24, where
# "always answer no" outscores an honest attempt.

_SUBJECT = {
    True: ["i think", "my sense is that", "i noticed that", "i'd say"],
    False: ["the team thinks", "it seems that", "records show that", "people say"],
}
_OBJECT = [
    "the meeting ran over",
    "the delivery arrived late",
    "the room was already occupied",
    "the report needs another pass",
    "the schedule slipped again",
    "the results came back clean",
]
_COLOR_OBJ = [
    "the {c} folder went missing",
    "the {c} door sticks badly",
    "the {c} labels came off",
    "the {c} chart was out of date",
    "the {c} binder is on the shelf",
    "the {c} form needs signing",
]
_NUMBER = ["14", "three", "seven", "22", "five", "nine"]


def _build_corpus():
    rng = random.Random(20260727)
    seen, out = set(), []
    # Enumerate feature combinations so the marginals are exact by
    # construction rather than by luck.
    combos = [(q, num, pol, col, name, fp)
              for q in (0, 1) for num in (0, 1) for pol in (0, 1)
              for col in (0, 1) for name in (0, 1) for fp in (0, 1)]
    rng.shuffle(combos)
    for i, (q, num, pol, col, name, fp) in enumerate(combos):
        color = COLORS[i % len(COLORS)]
        core = (_COLOR_OBJ[i % len(_COLOR_OBJ)].format(c=color) if col
                else _OBJECT[i % len(_OBJECT)])
        if num:
            core += f" by {_NUMBER[i % len(_NUMBER)]}"

        if q:
            lead = "do you think" if not fp else "do i take it"
            body = f"{lead} {core}"
        else:
            body = f"{rng.choice(_SUBJECT[bool(fp)])} {core}"

        parts = []
        if name:
            parts.append(f"{KEEPER_NAME},")
        if pol:
            # Discourse markers rather than an inline "please", which reads as
            # broken English in front of a first-person statement.
            parts.append("please —" if q else "thank you —")
        parts.append(body)

        msg = " ".join(parts)
        msg = msg[0].upper() + msg[1:] + ("?" if q else ".")
        if msg not in seen:
            seen.add(msg)
            out.append(msg)
    return out


HOLDOUT_MESSAGES = _build_corpus()


def holdout_labels(norm_name, n=24, seed=0):
    """A balanced (message, satisfies) set for behavioural scoring.

    Balanced per norm, so chance is 50% and a constant answer cannot score
    well. Returns fewer than n only if the corpus lacks positives or negatives.
    """
    rng = random.Random(seed ^ (hash(norm_name) & 0xFFFF))
    pos = [m for m in HOLDOUT_MESSAGES if satisfies(norm_name, m)]
    neg = [m for m in HOLDOUT_MESSAGES if not satisfies(norm_name, m)]
    rng.shuffle(pos)
    rng.shuffle(neg)
    k = min(n // 2, len(pos), len(neg))
    items = [(m, True) for m in pos[:k]] + [(m, False) for m in neg[:k]]
    rng.shuffle(items)
    return items


def holdout_balance(norm_name):
    labels = [lab for _, lab in holdout_labels(norm_name)]
    return sum(labels), len(labels)


# Vocabulary the guesser may use when writing its norm as a predicate. Each
# helper is bound to the message under test at evaluation time.
def predicate_helpers(msg):
    m = _norm(msg)
    words = _words(msg)
    return {
        "contains": lambda s: str(s).lower() in m,
        "wc": lambda: len(words),
        "has_digit": lambda: any(ch.isdigit() for ch in (msg or "")),
        "has_question_mark": lambda: "?" in (msg or ""),
        "endswith": lambda s: m.endswith(str(s).lower()),
        "startswith": lambda s: m.startswith(str(s).lower()),
        "len": len,
        "abs": abs,
        "min": min,
        "max": max,
        "any": any,
        "all": all,
    }


PREDICATE_VOCAB = """You may use only these, combined with and/or/not, comparisons and arithmetic:
  contains("x")        - is "x" somewhere in the message (case-insensitive)
  wc()                 - number of words in the message
  has_digit()          - does the message contain a digit
  has_question_mark()  - does the message contain a '?'
  startswith("x") / endswith("x")
Examples: 'has_question_mark()', 'wc() <= 8', 'contains("please") or contains("thank")'"""


def random_holdout(seed=0, n=12):
    rng = random.Random(seed)
    return rng.sample(HOLDOUT_MESSAGES, min(n, len(HOLDOUT_MESSAGES)))
